### ISSUE TITLE
Page routing does not work as intended

### ISSUE THREAD

**Issue by syahmiyani** [CaptainChemist/next-chop#2]
```
<Link href={`/${parentRoute}/${id}`}>
          <div>{images ? <GraphImg image={images} /> : null}</div>
 </Link>
```
Shouldnt it be `<a>` tag instead of `<div>` tag inside a `<Link>` tag to give that SPA feel . 
for example : 
```
import Link from 'next/link';

export default function Index() {
  return (
    <div>
      <Link href="/about">
        <a>About Page</a>
      </Link>
      <p>Hello Next.js</p>
    </div>
  );
}
```

**Comment by CaptainChemist** [comment]
Hi! I'm not exactly sure what you are asking- what do you mean by tag here? We are using the Link to nicely switch between different pages on the Gatsby site.

**Comment by syahmiyani** [comment]
Im sorry , I was under the assumption of this is a Nextjs project , I don't know what happen to my original post , I edited it. What I mean is , the page seems to be hard-reloaded on my end when I click the card. Im not familiar with Gatsby and how it do things but it definitely not how an SPA should feel.

**Comment by CaptainChemist** [comment]
I am super sorry I made a typo, this is a Next.js project. With that said though I'm not sure why you are seeing any hard-reloading. What I see when I click on a card is that I get a loading icon and then the recipe page displays. I have a production version of this running at: https://next-chop.codemochi.com/ so you can try it out there and see if you still are getting the hard refresh issue. I'm using chrome for what its worth.
